version: '3'
services:
  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - ${PWD}/storage:/var/lib/influxdb2:rw
    ports:
      - "127.0.0.1:8086:8086"
  # Use the influx cli to set up an influxdb instance. 
